# Generated by Django 2.2.1 on 2019-05-27 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('meme', '0001_initial'),
        ('favorite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritecollection',
            name='memes',
            field=models.ManyToManyField(to='meme.Meme'),
        ),
        migrations.AddField(
            model_name='userextension',
            name='favorite',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='favorite.FavoriteCollection'),
        ),
        migrations.AddField(
            model_name='userextension',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='userextension',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
