# Generated by Django 2.2.1 on 2019-05-27 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('favorite', '0002_auto_20190527_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextension',
            name='favorite',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='favorite.FavoriteCollection'),
        ),
    ]
